language: java
jdk:
  - openjdk8
  - openjdk11

sudo: required

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - sudo pip3 install -U pip

#don't build tags
branches:
  except:
    - /^v\d/

script:
  - ./gradlew build -s
  #- ./gradlew build -s && ./gradlew ciPerformRelease

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf ~/.gradle/caches/6.5.1/
  - find ~/.gradle/caches/ -name "*.lock" -type f -delete

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"